### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Deprane** [stickmanthe/roblox-follower-bot#3]
oog

**Comment by stickmanthe** [comment]
working

**Comment by stickmanthe** [comment]
what is not working???????

**Comment by stickmanthe** [comment]
hello

**Comment by Deprane** [comment]
> hello

hi srry im not someone active on here, it justs loads up the main page of my roblox acc and closes it and thats about it, these are the logs after the "logging in..."
![image](https://github.com/stickmanthe/roblox-follower-bot/assets/64393753/b834392b-d42e-4e70-8065-dced3d1dfa17)

**Comment by Deprane** [comment]
yes i did put my id in the txt file and it was the right password and user
